services:
  palworld-server:
    image: ghcr.io/pocketpairjp/palserver:latest
    # entrypoint: /pal/helper.sh
    command:
      - -port=8211
      - -useperfthreads
      - -NoAsyncLoadingThread
      - -UseMultithreadForDS
    ports:
      - "8211:8211/udp"
    volumes:
      - palworld-data:/pal/Package/Pal/Saved

volumes:
  palworld-data: